### PR TITLE
deps: updates wazero to 1.0.0-pre.3

### PR DESCRIPTION
**Pull request by codefromthecrypt**
This updates [wazero](https://wazero.io/) to [1.0.0-pre.3](https://github.com/tetratelabs/wazero/releases/tag/v1.0.0-pre.3). Note: wazero 1.0 will require Go 1.18+

Note: this also corrects memory as imported functions use the memory of the guest.

A later change can migrate host functions to use non-reflective syntax which might help performance here.

### CODE REVIEW

**Comment by codefromthecrypt** [comment]
bumped to 1.0.0-beta.1

**Comment by codefromthecrypt** [comment]
@christopher-kleine I had an old PR here so I updated it. If you have shelved this lemme know and I'll close it out!

**Comment by christopher-kleine** [comment]
Whoops!

I totally didn't notice this. Thanks for this. (Also I should fix the workflow)

**Comment by codefromthecrypt** [comment]
no worries. heads up I'll send another soon as we have monthly releases leading up to 1.0 early next year

**Pull request merged**
