### PR TITLE
deps: updates wazero to 1.0.0-pre.7

### PR DESCRIPTION
**Pull request by codefromthecrypt**
This updates [wazero](https://wazero.io/) to [1.0.0-pre.7](https://github.com/tetratelabs/wazero/releases/tag/v1.0.0-pre.7) and addresses the change where memory cannot be exported from a host module.

This works around the issue by making a wasm-defined memory, which imports the package "goenv". This also switches to non-reflective functions so that the performance is better. Finally, it aligns names from upstream.

Note: the linux build break I'm not sure about, but pong runs on my MacBook. It doesn't work properly because some rendering functions are not implemented, yet, but anyway it doesn't crash.

### CODE REVIEW

**Comment by codefromthecrypt** [comment]
ps I can't reproduce the build fail on darwin

**Comment by codefromthecrypt** [comment]
how I tested this (cloning this and https://github.com/aduros/wasm4.git into peer folders)

```bash
$ go install ./cmd/w4g/...
$ w4g run native ../wasm4/site/static/carts/pong.wasm
```

**Comment by codefromthecrypt** [comment]
Latest commit should fix the below on ubuntu

```
 # github.com/go-gl/glfw/v3.3/glfw
In file included from ./glfw/src/internal.h:188,
                 from ./glfw/src/context.c:30,
                 from ../../../go/pkg/mod/github.com/go-gl/glfw/v3.3/glfw@v0.0.0-20220622232848-a6c407ee30a0/c_glfw.go:4:
./glfw/src/x11_platform.h:36:10: fatal error: X11/Xcursor/Xcursor.h: No such file or directory
   36 | #include <X11/Xcursor/Xcursor.h>
      |          ^~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
github.com/hajimehoshi/ebiten/v2/internal/graphicsdriver/opengl/gl
# pkg-config --cflags  -- gl gl
Package gl was not found in the pkg-config search path.
Perhaps you should add the directory containing `gl.pc'
to the PKG_CONFIG_PATH environment variable
No package 'gl' found
Package gl was not found in the pkg-config search path.
Perhaps you should add the directory containing `gl.pc'
to the PKG_CONFIG_PATH environment variable
No package 'gl' found
pkg-config: exit status 1
```

**Comment by codefromthecrypt** [comment]
@christopher-kleine should be all ready now. very interesting project. I'm not sure exactly how to integration test this, but anyway quite cool.

**Comment by christopher-kleine** [comment]
Thanks! I'll check it out with more carts!

**Pull request merged**
